import Link from "next/link";
import { ArrowUpLeft, BookOpen, Sprout } from "lucide-react";
import type { Article } from "@/content/articles";
import { profile } from "@/content/profile";
import { routes } from "@/lib/constants";

type Props = { article: Article };

export function Body({ article }: Props) {
  return <div className="reading-grid"><aside className="reading-sidebar"><nav aria-label="فهرست این نوشته"><p><BookOpen aria-hidden="true" />در این نوشته</p><ol>{article.sections.map((section) => <li key={section.key}><a href={`#${section.key}`}>{section.title}</a></li>)}</ol><a href="#article-sources" className="quiet-link">منابع و وضعیت متن<ArrowUpLeft aria-hidden="true" /></a></nav></aside><div className="reading-body"><p className="reading-introduction">{article.introduction}</p>{article.sections.map((section) => <section id={section.key} key={section.key} aria-labelledby={`${section.key}-title`}><h2 id={`${section.key}-title`}>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.points && <ul>{section.points.map((point) => <li key={point}>{point}</li>)}</ul>}</section>)}<aside className="reading-takeaway" aria-labelledby="takeaway-title"><Sprout aria-hidden="true" /><div><h2 id="takeaway-title">چیزی که می‌توان همراه برد</h2><p>{article.takeaway}</p></div></aside><section id="article-sources" className="reading-sources" aria-labelledby="sources-title"><h2 id="sources-title">منابع این پیش‌نویس</h2><p>منابع زیر به زبان انگلیسی‌اند. متن حاضر، نگارش فارسیِ کمک‌گرفته از هوش مصنوعی است؛ ترجمهٔ رسمی منابع یا توصیهٔ درمانی شخصی نیست.</p><ul>{article.sources.map((source) => <li key={source.href}><a href={source.href} rel="noreferrer">{source.title}<ArrowUpLeft aria-hidden="true" /></a></li>)}</ul></section><aside className="author-note" aria-labelledby="author-title"><h2 id="author-title">وضعیت نویسندگی و بازبینی</h2><p>این پیش‌نویس هنوز نویسنده و بازبین حرفه‌ایِ تأییدشده ندارد و به‌عنوان نوشته یا توصیهٔ {profile.name} منتشر نشده است. تاریخ انتشار حرفه‌ای برای آن ثبت نشده؛ پیش از انتشار نهایی به بازبینی و تأیید نیاز دارد.</p><Link href={routes.about} className="quiet-link">آشنایی با {profile.name}<ArrowUpLeft aria-hidden="true" /></Link></aside></div></div>;
}
