import Link from "next/link";
import { ArrowUpLeft, BookOpen, Sprout } from "lucide-react";
import type { Article, Profile } from "@/lib/published";
import { routes } from "@/lib/constants";

type Props = { article: Article; profile: Profile };

export function Body({ article, profile }: Props) {
  return <div className="reading-grid"><aside className="reading-sidebar"><nav aria-label="فهرست این نوشته"><p><BookOpen aria-hidden="true" />در این نوشته</p><ol>{article.sections.map((section) => <li key={section.key}><a data-interact="control" href={`#${section.key}`}>{section.title}</a></li>)}</ol><a href="#article-sources" className="quiet-link">منابع و نویسنده<ArrowUpLeft aria-hidden="true" /></a></nav></aside><div className="reading-body"><p className="reading-introduction">{article.introduction}</p>{article.sections.map((section) => <section id={section.key} key={section.key} aria-labelledby={`${section.key}-title`}><h2 id={`${section.key}-title`}>{section.title}</h2>{section.paragraphs.map((paragraph, index) => <p key={`${section.key}-paragraph-${index}`}>{paragraph}</p>)}{section.points && <ul>{section.points.map((point, index) => <li key={`${section.key}-point-${index}`}>{point}</li>)}</ul>}</section>)}<aside className="reading-takeaway" aria-labelledby="takeaway-title"><Sprout aria-hidden="true" /><div><h2 id="takeaway-title">چیزی که می‌توان همراه برد</h2><p>{article.takeaway}</p></div></aside><section id="article-sources" className="reading-sources" aria-labelledby="sources-title"><h2 id="sources-title">منابع نوشته</h2><p>{article.sources.length ? "منابع معرفی‌شده برای مطالعهٔ بیشتر در ادامه آمده‌اند. این نوشته آموزش عمومی است، نه توصیهٔ درمانی شخصی." : "منبعی برای این نوشته ثبت نشده است. این نوشته آموزش عمومی است، نه توصیهٔ درمانی شخصی."}</p><ul>{article.sources.map((source) => <li key={source.href}><a href={source.href} rel="noreferrer">{source.title}<ArrowUpLeft aria-hidden="true" /></a></li>)}</ul></section><aside className="author-note" aria-labelledby="author-title"><h2 id="author-title">نویسنده و وضعیت انتشار</h2><p>نویسنده: {article.author}. این متن پس از بازبینی برای مطالعهٔ عمومی منتشر شده است؛ برای تشخیص یا تصمیم درمانی فردی کافی نیست.</p>{article.author === profile.name && <Link href={routes.about} className="quiet-link">آشنایی با {profile.name}<ArrowUpLeft aria-hidden="true" /></Link>}</aside></div></div>;
}
