"use client";

import { useId } from "react";
import { Controller, useFieldArray, type UseFormReturn } from "react-hook-form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { formatNumber } from "@/lib/format";
import type { Editor } from "@/lib/publishing";

type Props = { form: UseFormReturn<Editor>; onEdit: () => void };

export function ArticleFields({ form, onEdit }: Props) {
  const id = useId();
  const { register, control, getFieldState, formState } = form;
  const sections = useFieldArray({ control, name: "record.sections" });
  const sources = useFieldArray({ control, name: "record.sources" });
  return <><label htmlFor={`${id}-intro`}>مقدمه</label><Textarea id={`${id}-intro`} {...register("record.introduction")} rows={5} maxLength={4000} aria-invalid={getFieldState("record.introduction", formState).invalid} /><p className="field-error">{getFieldState("record.introduction", formState).invalid ? "مقدمه باید ۱ تا ۴۰۰۰ نویسه باشد." : ""}</p><div className="panel-heading"><h3>بخش‌های مقاله</h3><Button type="button" variant="outline" disabled={sections.fields.length >= 30} onClick={() => { onEdit(); sections.append({ key: "", title: "", paragraphs: [""], points: [] }); }}>افزودن بخش</Button></div><p className="panel-note">۱ تا ۳۰ بخش؛ پاراگراف‌ها را با یک خط خالی جدا کنید. هر نکته در یک خط، حداکثر ۲۰ پاراگراف و ۲۰ نکته در هر بخش.</p>
    {sections.fields.map((section, index) => <section className="editor-block" key={section.id}><h4>بخش {formatNumber(index + 1)}</h4><label htmlFor={`${id}-key-${index}`}>شناسهٔ لاتین و یکتای بخش</label><Input id={`${id}-key-${index}`} {...register(`record.sections.${index}.key`)} dir="ltr" maxLength={100} aria-invalid={getFieldState(`record.sections.${index}.key`, formState).invalid} /><label htmlFor={`${id}-title-${index}`}>عنوان بخش</label><Input id={`${id}-title-${index}`} {...register(`record.sections.${index}.title`)} maxLength={160} aria-invalid={getFieldState(`record.sections.${index}.title`, formState).invalid} /><label htmlFor={`${id}-body-${index}`}>پاراگراف‌ها؛ هر کدام حداکثر ۴۰۰۰ نویسه</label><Controller control={control} name={`record.sections.${index}.paragraphs`} render={({ field, fieldState }) => <Textarea ref={field.ref} name={field.name} id={`${id}-body-${index}`} rows={7} value={field.value.join("\n\n")} onBlur={field.onBlur} onChange={(event) => field.onChange(event.target.value.split("\n\n"))} aria-invalid={fieldState.invalid} />} /><label htmlFor={`${id}-points-${index}`}>نکته‌ها، اختیاری</label><Controller control={control} name={`record.sections.${index}.points`} render={({ field, fieldState }) => <Textarea ref={field.ref} name={field.name} id={`${id}-points-${index}`} rows={3} value={field.value?.join("\n") ?? ""} onBlur={field.onBlur} onChange={(event) => field.onChange(event.target.value === "" ? [] : event.target.value.split("\n"))} aria-invalid={fieldState.invalid} />} /><p className="field-error">{getFieldState(`record.sections.${index}`, formState).invalid ? "عنوان، شناسه و متن این بخش را مطابق محدودیت‌ها بررسی کنید." : ""}</p><div className="member-actions"><Button type="button" variant="outline" disabled={index === 0} onClick={() => { onEdit(); sections.move(index, index - 1); }} aria-label={`بالابردن بخش ${formatNumber(index + 1)}`}>بالاتر</Button><Button type="button" variant="outline" disabled={index === sections.fields.length - 1} onClick={() => { onEdit(); sections.move(index, index + 1); }} aria-label={`پایین‌بردن بخش ${formatNumber(index + 1)}`}>پایین‌تر</Button><Button type="button" variant="outline" disabled={sections.fields.length <= 1} onClick={() => { onEdit(); sections.remove(index); }}>برداشتن این بخش</Button></div></section>)}
    <p className="field-error">{getFieldState("record.sections", formState).invalid ? "بخش‌ها باید کامل، در محدودهٔ تعداد و با شناسه‌های یکتا باشند." : ""}</p><label htmlFor={`${id}-takeaway`}>جمع‌بندی</label><Textarea id={`${id}-takeaway`} {...register("record.takeaway")} rows={4} maxLength={4000} aria-invalid={getFieldState("record.takeaway", formState).invalid} /><p className="field-error">{getFieldState("record.takeaway", formState).invalid ? "جمع‌بندی باید ۱ تا ۴۰۰۰ نویسه باشد." : ""}</p><div className="panel-heading"><h3>منابع</h3><Button type="button" variant="outline" disabled={sources.fields.length >= 20} onClick={() => { onEdit(); sources.append({ title: "", href: "" }); }}>افزودن منبع</Button></div><p className="panel-note">حداکثر ۲۰ منبع با نشانی HTTPS؛ هیچ نشانی در سرور واکشی نمی‌شود.</p>{sources.fields.map((source, index) => <div className="editor-block" key={source.id}><label htmlFor={`${id}-source-${index}`}>عنوان منبع {formatNumber(index + 1)}</label><Input id={`${id}-source-${index}`} {...register(`record.sources.${index}.title`)} maxLength={160} aria-invalid={getFieldState(`record.sources.${index}.title`, formState).invalid} /><label htmlFor={`${id}-href-${index}`}>نشانی منبع</label><Input id={`${id}-href-${index}`} {...register(`record.sources.${index}.href`)} dir="ltr" type="url" maxLength={500} aria-invalid={getFieldState(`record.sources.${index}.href`, formState).invalid} /><p className="field-error">{getFieldState(`record.sources.${index}`, formState).invalid ? "عنوان ۲ تا ۱۶۰ نویسه و نشانی HTTPS بدون اطلاعات ورود لازم است." : ""}</p><Button type="button" variant="outline" onClick={() => { onEdit(); sources.remove(index); }}>برداشتن منبع {formatNumber(index + 1)}</Button></div>)}</>;
}
