import Link from "next/link";
import { BookOpen, Plus } from "lucide-react";
import { ContentFilter } from "./content-filter";
import { Photo } from "@/components/shared/photo";
import { RefreshButton } from "@/components/shared/refresh-button";
import { Button } from "@/components/ui/button";
import { images } from "@/content/images";
import { routes, topics, publicationStates } from "@/lib/constants";
import { buildContent, contentLabels, contentPaths, type ContentList as Catalog } from "@/lib/publishing";
import { formatDate, formatNumber } from "@/lib/format";

type Props = { snapshot: Catalog; isLoading?: boolean };

export function ContentList({ snapshot, isLoading = false }: Props) {
  const { kind, query } = snapshot;
  return <>{isLoading && <p className="load-status" role="status">در حال دریافت محتوا…</p>}<main className="admin-records" id="main-content" inert={isLoading} aria-busy={isLoading}><div className="dashboard-title"><div><nav className="breadcrumbs" aria-label="مسیر صفحه"><Link href={routes.admin}>مدیریت</Link><span aria-hidden="true">/</span><span aria-current="page">{contentLabels[kind]}</span></nav><h1>مدیریت {contentLabels[kind]}</h1><p>پیش‌نویس، بازبینی و انتشار با تصمیم روشن شما.</p></div><RefreshButton /></div><section className="dashboard-panel"><div className="panel-heading"><h2>پیداکردن محتوا</h2><BookOpen aria-hidden="true" /></div>{snapshot.hasError && <p role="status" className="member-feedback">فیلتر نشانی معتبر نبود؛ نمای پیش‌فرض نمایش داده شد.</p>}<ContentFilter key={buildContent(kind, query)} kind={kind} query={query} /></section><section className="dashboard-panel"><div className="panel-heading"><h2>{formatNumber(snapshot.count)} نوشته</h2><Button asChild><Link prefetch={false} href={`${contentPaths[kind]}/new`}><Plus aria-hidden="true" />{kind === "article" ? "مقالهٔ تازه" : "دورهٔ تازه"}</Link></Button></div>{snapshot.entries.length ? <ul className="content-grid">{snapshot.entries.map((entry) => <li key={entry.id}><Photo image={images[entry.image]} sizes="(min-width: 1200px) 330px, (min-width: 600px) 45vw, 90vw" /><div className="content-copy"><span className="visit-state" data-state={entry.status === publicationStates.published ? "confirmed" : "pending"}>{entry.status === publicationStates.published ? "منتشرشده" : "پیش‌نویس"}</span><h3>{entry.title}</h3><p>{topics[entry.category]}</p><p>آخرین ویرایش: <time dateTime={entry.updatedAt}>{formatDate(new Date(entry.updatedAt), { dateStyle: "medium", timeStyle: "short" })}</time></p><p className="content-slug"><bdi>{entry.slug}</bdi></p><Button asChild variant="outline"><Link prefetch={false} href={`${contentPaths[kind]}/${entry.id}`} aria-label={`ویرایش ${entry.title}`}>بازکردن ویرایشگر</Link></Button></div></li>)}</ul> : <p className="dashboard-empty">محتوایی مطابق این فیلتر وجود ندارد؛ دادهٔ نمونه جای آن نمایش داده نمی‌شود.</p>}<nav className="record-pagination" aria-label="صفحه‌های محتوا">{query.page > 1 && <Link prefetch={false} scroll={false} href={buildContent(kind, { ...query, page: query.page - 1 })}>صفحهٔ قبل</Link>}<span>{formatNumber(query.page)} از {formatNumber(snapshot.pageCount)}</span>{query.page < snapshot.pageCount && <Link prefetch={false} scroll={false} href={buildContent(kind, { ...query, page: query.page + 1 })}>صفحهٔ بعد</Link>}</nav>{snapshot.count > 8000 && <p>سقف پیمایش هزار صفحه است؛ جست‌وجو یا موضوع را محدود کنید.</p>}<p className="panel-note">تعداد و فهرست تراکنش واحد نیستند؛ هنگام تغییر هم‌زمان ممکن است تا تازه‌سازی اختلاف کوتاهی دیده شود.</p></section></main></>;
}
