import Link from "next/link";
import { ArrowUpLeft, CalendarDays, ChartNoAxesCombined, Clock3, Mail, ShieldCheck, Users } from "lucide-react";
import { Photo } from "@/components/shared/photo";
import { Button } from "@/components/ui/button";
import { LiveNumber } from "./live-number";
import { VisitChart } from "./visit-chart";
import { ScheduleList } from "./schedule-list";
import { MessagePreview } from "./message-preview";
import { images } from "@/content/images";
import { formatDate, formatNumber } from "@/lib/format";
import { getInstant } from "@/lib/slots";
import { routes } from "@/lib/constants";
import type { Dashboard as Overview } from "@/lib/admin";

type Props = { snapshot: Overview; name: string; isLoading?: boolean };

export function Dashboard({ snapshot, name, isLoading = false }: Props) {
  const requestChange = snapshot.requests - snapshot.previousRequests;
  const clientChange = snapshot.newClients - snapshot.previousClients;
  const stats = [
    { label: "نوبت‌های فعال امروز", value: snapshot.todayCount, icon: CalendarDays, note: "در انتظار تأیید و تأییدشده", tone: "violet" },
    { label: "درخواست‌های هفت روز", value: snapshot.requests, icon: ChartNoAxesCombined, note: requestChange === 0 ? "برابر با هفت روز پیش از آن" : `${formatNumber(Math.abs(requestChange))} ${requestChange < 0 ? "کمتر" : "بیشتر"} از هفت روز پیش از آن`, tone: "rose" },
    { label: "حساب‌های مراجعان", value: snapshot.clients, icon: Users, note: `${formatNumber(snapshot.newClients)} حساب تازه؛ ${clientChange === 0 ? "برابر با بازهٔ قبلی" : `${formatNumber(Math.abs(clientChange))} ${clientChange < 0 ? "کمتر" : "بیشتر"} از بازهٔ قبلی`}`, tone: "teal" },
    { label: "پیام‌های خوانده‌نشده", value: snapshot.unread, icon: Mail, note: "وضعیت فعلیِ ثبت‌شده در پایگاه‌داده", tone: "amber" },
  ];
  return <>{isLoading && <p className="load-status" role="status">در حال دریافت داشبورد…</p>}<main id="main-content" className="dashboard" inert={isLoading} aria-busy={isLoading}>
    <div className="dashboard-title"><div><nav className="breadcrumbs" aria-label="مسیر داشبورد"><span>مدیریت</span><span aria-hidden="true">/</span><span aria-current="page">داشبورد</span></nav><h1>نگاهی به امروز</h1></div></div>
    <section className="admin-greeting" aria-labelledby="greeting-title"><Photo image={images.desk} sizes="(min-width: 1600px) 1440px, 100vw" className="greeting-photo" /><div className="greeting-veil" aria-hidden="true" /><div className="greeting-copy"><p className="section-eyebrow">{formatDate(getInstant(snapshot.day, "12:00"), { weekday: "long", day: "numeric", month: "long", year: "numeric" })}</p><h2 id="greeting-title">خوش آمدید، {name}.</h2><p>برای هر گفت‌وگو، فرصتی برای توجه.</p><p className="greeting-task">{formatNumber(snapshot.pendingCount)} نوبت آینده در انتظار تأیید است.</p><Button asChild><a href="#schedule-today">دیدن برنامهٔ امروز<ArrowUpLeft aria-hidden="true" /></a></Button></div><span className="visual-caption">تصویر مفهومی؛ فضای واقعی مطب نیست.</span></section>
    <section className="dashboard-stats" aria-label="آمار ثبت‌شده">{stats.map(({ label, value, icon: Icon, note, tone }) => <article className="stat-card" data-tone={tone} key={label}><span className="stat-icon"><Icon aria-hidden="true" /></span><h2>{label}</h2><LiveNumber value={value} /><p>{note}</p></article>)}</section>
    <p className="dashboard-caption">بازهٔ هفت‌روزه شامل امروزِ هنوز کامل‌نشده است. آمار درخواست‌ها همهٔ وضعیت‌ها، حتی لغوشده، را در بر می‌گیرد. شمار حساب‌ها به معنی تعداد افرادِ دریافت‌کنندهٔ درمان نیست.</p>
    <div className="dashboard-grid"><section className="dashboard-panel today-panel" id="schedule-today" aria-labelledby="today-title"><div className="panel-heading"><div><p className="section-eyebrow">به وقت تهران</p><h2 id="today-title">برنامهٔ امروز</h2></div><span className="panel-count">{formatNumber(snapshot.todayCount)} نوبت</span></div><ScheduleList entries={snapshot.today} /><p className="panel-note">حداکثر شش نوبت، از ابتدای روز؛ گذشتن ساعت به‌تنهایی وضعیت را تغییر نمی‌دهد. برای جزئیات و تغییر، فهرست نوبت‌ها را باز کنید.</p></section>
    <section className="dashboard-panel chart-panel" aria-labelledby="chart-title"><div className="panel-heading"><div><p className="section-eyebrow">هفت روز گذشته تا امروز</p><h2 id="chart-title">نوبت‌ها بر پایهٔ روز جلسه</h2></div><ChartNoAxesCombined aria-hidden="true" /></div><VisitChart daily={snapshot.daily} /><p className="panel-note">همهٔ وضعیت‌ها، از جمله لغوشده؛ این نمودار تعداد جلسه‌های برگزارشده یا تعداد درخواست‌های ثبت‌شده در هر روز نیست.</p><details className="chart-values"><summary>دیدن عددهای نمودار</summary><table><caption>تعداد نوبت‌ها بر اساس روز جلسه</caption><thead><tr><th scope="col">روز</th><th scope="col">تعداد</th></tr></thead><tbody>{snapshot.daily.map((entry) => <tr key={entry.day}><th scope="row">{entry.label}</th><td>{formatNumber(entry.count)}</td></tr>)}</tbody></table></details></section>
    <section className="dashboard-panel" aria-labelledby="upcoming-title"><div className="panel-heading"><div><p className="section-eyebrow">پس از امروز</p><h2 id="upcoming-title">نوبت‌های پیش رو</h2></div><Clock3 aria-hidden="true" /></div><ScheduleList entries={snapshot.upcoming} isDated /><p className="panel-note">حداکثر پنج نوبت فعال بعدی؛ این نمای کوتاه، کل برنامه نیست.</p></section>
    <section className="dashboard-panel messages-panel" id="message-preview" aria-labelledby="messages-title"><div className="panel-heading"><div><p className="section-eyebrow">خلاصه، بدون متن حساس</p><h2 id="messages-title">پیام‌های تازه</h2></div><Mail aria-hidden="true" /></div><MessagePreview messages={snapshot.messages} /><p className="panel-note">حداکثر چهار پیام خوانده‌نشده. این نمایش چیزی را خوانده‌شده علامت نمی‌زند و پاسخی ارسال نمی‌کند؛ برای خواندن و تغییر وضعیت، پیام را در صندوق باز کنید.</p></section>
    <section className="dashboard-panel activity-panel" id="recent-activity" aria-labelledby="activity-title"><div className="panel-heading"><div><p className="section-eyebrow">از روی زمان به‌روزرسانی</p><h2 id="activity-title">تغییرهای اخیر</h2></div></div>{snapshot.activity.length ? <ol className="activity-list">{snapshot.activity.map((entry) => <li key={entry.key}><span aria-hidden="true" /><div><p>{entry.label}</p><time dateTime={entry.at}>{formatDate(new Date(entry.at), { day: "numeric", month: "long", hour: "2-digit", minute: "2-digit" })}</time></div></li>)}</ol> : <p className="dashboard-empty">هنوز رکوردی برای این خلاصه وجود ندارد.</p>}<p className="panel-note">آخرین نسخهٔ حداکثر شش رکورد پیام/نوبت؛ این فهرست، تاریخچهٔ کامل رخدادها یا گزارش ممیزی نیست.</p></section>
    <section className="dashboard-panel quick-panel" aria-labelledby="quick-title"><div className="panel-heading"><div><p className="section-eyebrow">دسترسی روشن</p><h2 id="quick-title">کارهای سریع</h2></div></div><div className="quick-links"><Link data-interact="control" href={routes.inbox} prefetch={false}>صندوق پیام‌ها<ArrowUpLeft aria-hidden="true" /></Link><Link data-interact="control" href={routes.reviews} prefetch={false}>بررسی دیدگاه‌ها<ArrowUpLeft aria-hidden="true" /></Link><Link data-interact="control" href={routes.adminSettings} prefetch={false}>تنظیمات سایت<ArrowUpLeft aria-hidden="true" /></Link><Link data-interact="control" href={routes.adminArticles} prefetch={false}>مدیریت مقالات<ArrowUpLeft aria-hidden="true" /></Link><Link data-interact="control" href={routes.adminCourses} prefetch={false}>مدیریت دوره‌ها<ArrowUpLeft aria-hidden="true" /></Link><Link data-interact="control" href={routes.agenda} prefetch={false}>مدیریت نوبت‌ها<ArrowUpLeft aria-hidden="true" /></Link><Link data-interact="control" href={routes.clients} prefetch={false}>حساب‌های مراجعان<ArrowUpLeft aria-hidden="true" /></Link><Link data-interact="control" href={routes.settings} prefetch={false}>ویرایش حساب خودم<ArrowUpLeft aria-hidden="true" /></Link><Link data-interact="control" href={routes.home} prefetch={false}>دیدن وب‌سایت<ArrowUpLeft aria-hidden="true" /></Link><a data-interact="control" href="#message-preview">خلاصهٔ پیام‌ها<ArrowUpLeft aria-hidden="true" /></a></div><div className="admin-privacy"><ShieldCheck aria-hidden="true" /><p>اطلاعات این صفحه خصوصی‌اند. فقط برای هماهنگی ضروری استفاده کنید؛ روی دستگاه مشترک از حساب خارج شوید.</p></div></section></div>
    <p className="dashboard-caption">زمان آغاز این خواندن: <time dateTime={snapshot.checkedAt}>{formatDate(new Date(snapshot.checkedAt), { dateStyle: "medium", timeStyle: "short" })}</time> · خواندن بخش‌ها تراکنش واحد نیست؛ هنگام تغییر هم‌زمان ممکن است تا تازه‌سازی بعدی اختلاف کوتاهی دیده شود. چراغ اتصال، تضمین تازه‌بودن همهٔ داده‌ها نیست.</p>
  </main></>;
}
