import Link from "next/link";
import { CalendarDays } from "lucide-react";
import { AgendaFilter } from "./agenda-filter";
import { VisitSheet } from "./visit-sheet";
import { services } from "@/content/services";
import { agendaDateSchema, agendaViews, buildAgenda, type Agenda as Schedule } from "@/lib/agenda";
import { routes } from "@/lib/constants";
import { appointmentLabels } from "@/lib/visits";
import { formatDate, formatNumber } from "@/lib/format";
import { addDays, getInstant } from "@/lib/slots";

type Props = { snapshot: Schedule; isLoading?: boolean };
const viewLabels = { table: "جدول", week: "هفته", month: "ماه" };

export function Agenda({ snapshot, isLoading = false }: Props) {
  const { query, range, entries } = snapshot;
  const days: string[] = [];
  for (let day = range.from; day <= range.to && days.length < 32; day = addDays(day, 1)) days.push(day);
  const offset = (new Date(`${range.from}T12:00:00Z`).getUTCDay() + 1) % 7;
  const weekdays = ["شنبه", "یکشنبه", "دوشنبه", "سه‌شنبه", "چهارشنبه", "پنجشنبه", "جمعه"];
  return <>{isLoading && <p className="load-status" role="status">در حال دریافت نوبت‌ها…</p>}<main id="main-content" className="admin-records" inert={isLoading} aria-busy={isLoading}><div className="dashboard-title"><div><nav className="breadcrumbs" aria-label="مسیر صفحه"><Link href={routes.admin}>مدیریت</Link><span aria-hidden="true">/</span><span aria-current="page">نوبت‌ها</span></nav><h1>نوبت‌ها، با یک نگاه</h1><p>برنامهٔ ثبت‌شده؛ نه زمان‌های آزاد رزرو. همهٔ ساعت‌ها به وقت تهران‌اند.</p></div></div>
    <section className="dashboard-panel"><div className="panel-heading"><h2>برنامه و فیلترها</h2><CalendarDays aria-hidden="true" /></div>{snapshot.hasError && <p role="status" className="member-feedback">نشانی فیلتر معتبر نبود؛ نمای پیش‌فرض نمایش داده شد.</p>}<AgendaFilter key={buildAgenda(query)} query={query} services={services.map(({ key, title }) => ({ key, title }))} /><nav className="record-tabs" aria-label="نمای نوبت‌ها">{Object.entries(viewLabels).map(([view, label]) => <Link key={view} prefetch={false} scroll={false} aria-current={query.view === view ? "page" : undefined} href={buildAgenda({ ...query, view: view as keyof typeof viewLabels, page: 1 })}>{label}</Link>)}</nav><div className="range-bar"><strong>{formatDate(getInstant(range.from, "12:00"))} تا {formatDate(getInstant(range.to, "12:00"))}</strong><nav aria-label="بازهٔ برنامه">{agendaDateSchema.safeParse(range.previous).success && <Link prefetch={false} scroll={false} href={buildAgenda({ ...query, date: range.previous, page: 1 })}>بازهٔ قبل</Link>}<Link prefetch={false} scroll={false} href={buildAgenda({ ...query, date: snapshot.today, page: 1 })}>امروز</Link>{agendaDateSchema.safeParse(range.next).success && <Link prefetch={false} scroll={false} href={buildAgenda({ ...query, date: range.next, page: 1 })}>بازهٔ بعد</Link>}</nav></div>{query.client && <p className="panel-note">فقط حساب با شناسهٔ <bdi>{query.client}</bdi> · <Link href={buildAgenda({ ...query, client: "", page: 1 })}>برداشتن فیلتر حساب</Link></p>}{query.q && query.view === agendaViews.table && <p className="panel-note">جست‌وجوی شناسه در تمام تاریخ‌ها انجام شده است؛ بازهٔ بالا روی این نتیجه اعمال نمی‌شود.</p>}<p className="panel-note">{formatNumber(snapshot.count)} نوبت مطابق فیلتر · هفته از شنبه آغاز می‌شود. ترتیب در تقویم، درون هر روز اعمال می‌شود.</p></section>
    {query.view === agendaViews.table ? <section className="dashboard-panel"><h2>فهرست نوبت‌ها</h2>{entries.length ? <div className="record-table" tabIndex={0} role="region" aria-label="جدول نوبت‌ها؛ در عرض کم قابل پیمایش"><table><caption className="sr-only">نتیجهٔ فیلتر نوبت‌ها</caption><thead><tr><th scope="col">مراجع و جلسه</th><th scope="col">زمان تهران</th><th scope="col">وضعیت</th><th scope="col">اقدام</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id}><th scope="row"><strong>{entry.name}</strong><span>{services.find((service) => service.key === entry.service)?.title}</span></th><td><time dateTime={entry.startsAt}>{formatDate(new Date(entry.startsAt), { dateStyle: "medium", timeStyle: "short" })}</time></td><td><span className="visit-state" data-state={entry.status}>{appointmentLabels[entry.status]}</span></td><td><VisitSheet entry={entry} title={services.find((service) => service.key === entry.service)?.title ?? "جلسهٔ مشاوره"} checkedAt={snapshot.checkedAt} /></td></tr>)}</tbody></table></div> : <p className="dashboard-empty">نوبتی مطابق این فیلتر پیدا نشد. این نتیجه به معنی آزادبودن ساعت‌ها نیست.</p>}<nav className="record-pagination" aria-label="صفحه‌های نوبت‌ها">{query.page > 1 && <Link prefetch={false} scroll={false} href={buildAgenda({ ...query, page: query.page - 1 })}>صفحهٔ قبل</Link>}<span>صفحهٔ {formatNumber(query.page)} از {formatNumber(snapshot.pageCount)}</span>{query.page < snapshot.pageCount && <Link prefetch={false} scroll={false} href={buildAgenda({ ...query, page: query.page + 1 })}>صفحهٔ بعد</Link>}</nav>{snapshot.count > 8000 && <p className="panel-note">فقط هزار صفحهٔ نخست قابل پیمایش است؛ برای رسیدن به بقیه، فیلتر را محدود کنید.</p>}</section>
      : snapshot.isLimited ? <section className="dashboard-panel"><h2>تقویم این بازه نمایش داده نشد</h2><p role="status" className="member-feedback">تعداد نتایج از سقف چهار هزار نوبت بیشتر است. برای جلوگیری از نمایش ناقص، هیچ روزی خالی یا آزاد نشان داده نمی‌شود. فیلتر محدودتری انتخاب کنید یا جدول صفحه‌بندی‌شده را باز کنید.</p><Link className="quiet-link" prefetch={false} href={buildAgenda({ ...query, view: agendaViews.table, page: 1 })}>جدول با همین فیلترها و بازهٔ ۳۲روزه</Link></section> : <section className="dashboard-panel"><h2>{query.view === agendaViews.month ? "تقویم ماه خورشیدی" : "برنامهٔ هفته"}</h2><div className="agenda-calendar" data-view={query.view}><div className="calendar-weekdays" aria-hidden="true">{weekdays.map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-days">{query.view === agendaViews.month && Array.from({ length: offset }, (_, index) => <div key={`empty-${index}`} className="calendar-blank" aria-hidden="true" />)}{days.map((day) => { const visits = entries.filter((entry) => entry.date === day); return <section className="calendar-day" data-today={day === snapshot.today} key={day}><h3><time dateTime={day}>{formatDate(getInstant(day, "12:00"), { weekday: "long", day: "numeric", month: "long" })}</time><small>{formatNumber(visits.length)} نوبت</small></h3>{visits.length ? <ul>{visits.map((entry) => <li key={entry.id}><time dateTime={entry.startsAt}>{formatDate(new Date(entry.startsAt), { hour: "2-digit", minute: "2-digit" })}</time><strong>{entry.name}</strong><span className="visit-state" data-state={entry.status}>{appointmentLabels[entry.status]}</span><VisitSheet entry={entry} title={services.find((service) => service.key === entry.service)?.title ?? "جلسهٔ مشاوره"} checkedAt={snapshot.checkedAt} /></li>)}</ul> : <p>نوبت مطابق فیلتر ندارد.</p>}</section>; })}</div></div></section>}
    <p className="dashboard-caption">زمان آغاز خواندن: <time dateTime={snapshot.checkedAt}>{formatDate(new Date(snapshot.checkedAt), { dateStyle: "medium", timeStyle: "short" })}</time> · خواندن تعداد و فهرست تراکنش واحد نیست. اطلاعات خصوصی‌اند؛ چراغ اتصال تضمین تازه‌بودن داده نیست.</p></main></>;
}
